config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  delete "pools/:id", to: "pools#destroy", as: :delete_pool

  resources :pools, except: [:destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: :destroy
  # resources :dashboards, only: :show
  get "dashboards", to: "dashboards#show"
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pool

  validates :start_date, presence: true
  validates :end_date, presence: true

end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  # has_many_attached :photos
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  CATEGORIES = %w[jacuzzi olympic slides wavepool indoor outdoor natural infinity lap heated salty kids\ friendly]

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :price, presence: true
  validates :location, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :pools

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization
  add_flash_types :search_notice
  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @booking = Booking.new(booking_params)
    @pool = Pool.find(params[:pool_id])
    @booking.pool = @pool
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to dashboards_path, notice: "You have succesfully booked this pool. Happy swimming :)"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    authorize @booking
    @booking.destroy
    redirect_to dashboards_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @pools = current_user.pools
    authorize @pools
    @bookings = current_user.bookings
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @pools = policy_scope(Pool)
    sql_query = "location ILIKE :query OR category ILIKE :query"
    if Pool.where(sql_query, query: "%#{params[:query]}%").empty?
      redirect_to root_path, search_notice: "There are no pools matching your search, please start again!"
    elsif params[:query].present?
      @pools = Pool.where(sql_query, query: "%#{params[:query]}%")
    else
      @pools = Pool.all
    end

    @markers = @pools.geocoded.map do |pool|
      {
        lat: pool.latitude,
        lng: pool.longitude
      }
    end
  end

  def show
    @pool = Pool.find(params[:id])
    authorize @pool
    @booking = Booking.new
  end

  def new
    @pool = Pool.new
    authorize @pool
  end

  def create
    @pool = Pool.new(pool_params)
    @pool.user = current_user
    authorize @pool
    if @pool.save
      redirect_to pool_path(@pool)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pool = Pool.find(params[:id])
    authorize @pool
  end

  def update
    @pool = Pool.find(params[:id])
    authorize @pool
    @pool.update(pool_params)
    redirect_to pool_path(@pool)
  end

  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy
    authorize @pool
    redirect_to dashboards_path, status: :see_other
  end

  private

  def pool_params
    params.require(:pool).permit(:name, :description, :price, :category, :location, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<h2>Book this pool</h2>

<%= simple_form_for [@pool, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/dashboards/show.html.erb
<div class="container">
  <h1 class="pt-5 pb-2">Dashboard</h1>
  <div class="booking-container">
    <h4 class="pt-4 pb-2">My upcoming bookings</h4>
    <div class="booking-grid">
    <% @bookings.reverse.each do |booking| %>
      <div class="pool-card mb-3">
        <% if booking.pool.photo.attached? %>
          <%= cl_image_tag booking.pool.photo.key, width: 500, crop: :fill %>
        <% else %>
          <img src="https://images.unsplash.com/photo-1536745511564-a5fa6e596e7b?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=992" alt="Pool photo" height=200>
        <% end %>
        <div class="p-4">
          <h4><%= booking.pool.name %></h4>
          <p><i class="fa-regular fa-calendar-days"></i> <%= booking.start_date %> <i class="fa-solid fa-arrow-right-long"></i> <%= booking.end_date %></p>
          <ul>
            <li><i class="fa-solid fa-location-dot"></i> <%= booking.pool.location %></li>
          </ul>
        </div>
        <%= link_to "x", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-outline-dark btn-sm delete' %>
      </div>
    <% end %>
    </div>
  </div>
  <hr class="mt-5 mb-4">
  <div class="d-flex justify-content-between align-items-center">
    <h4 class="pt-4 pb-2">My pools</h4>
  </div>
  <div class="booking-grid">
    <% @pools.each do |pool| %>
      <div class="pool-card mb-3">
        <%= link_to pool_path(pool) do %>
          <div>
            <% if pool.photo.attached? %>
              <%= cl_image_tag pool.photo.key, width: 500, crop: :fill %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1536745511564-a5fa6e596e7b?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=992" alt="Pool photo" height=200>
            <% end %>
            <div class="p-4">
              <div class="d-flex justify-content-between align-items-center">
                <div>
                  <p class="category"><%= pool.category %></p>
                  <h4 class="truncate"><%= pool.name %></h4>
                </div>
              </div>
              <ul class="details d-flex justify-content-between">
                <li class="truncate"><%= pool.location %></li>
                <li class="rating"><i class="fa-solid fa-star"></i> <%= pool.rating %></i></li>
                <li class="price"><strong><%= pool.price %> €</strong></li>
              </ul>
            </div>
          </div>
        <% end %>
        <%= link_to "x", delete_pool_path(pool), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'btn btn-outline-dark btn-sm delete' %>
      </div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SwimInPool</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <% if request.path == '/' %>
      <p class="notice home-notice"><%= notice %></p>
      <p class="notice search-notice-home"><%= search_notice %></p>
      <%= render "shared/navbar" %>
      <div class="content-container">
        <%= yield %>
      </div>
    <% else %>
      <div class="page-container">
        <div class="navbar-container">
          <%= render "shared/navbar" %>
        </div>
        <div class="content-container">
          <p class="notice"><%= notice %></p>
          <%= yield %>
        </div>
        <div class="footer-container">
          <%= render "shared/footer" %>
        </div>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner">
  <div class="header">
    <h1 class="mb-4">Book cool pools</h1>
    <%= form_tag pools_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a pool"
      %>
      <%= submit_tag "Search", class: "btn btn-primary pool" %>
    <% end %>
  </div>
</div>

app/views/pools/_form.html.erb
  <%= simple_form_for @pool do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :location %>
    <%= f.input :category, collection: Pool::CATEGORIES %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
  <br>
  <%= link_to "< Back to dashboard ", dashboards_path %>

app/views/pools/edit.html.erb
<div class="container">
  <h2>Make changes to your pool</h2>
  <%= render "form" %>
</div>

app/views/pools/index.html.erb
<div class="d-flex justify-content-between">
  <div class="search-results px-5">
    <div class="d-flex justify-content-between align-items-center mt-5 pb-3">
      <h1>Discover all pools</h1>
    </div>
    <div class="cards-container">
      <% @pools.reverse.each do |pool| %>
        <%= link_to pool_path(pool) do %>
          <div class="pool-card mb-3">
            <% if pool.photo.attached? %>
              <%= cl_image_tag pool.photo.key, width: 500, crop: :fill %>
            <% else %>
              <img src="https://images.unsplash.com/photo-1536745511564-a5fa6e596e7b?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=992" alt="Pool photo" height=200>
            <% end %>
            <div class="p-4">
              <div>
                <p class="category"><%= pool.category %></p>
                <h4 class="truncate"><%= pool.name %></h4>
              </div>
                <ul class="details d-flex justify-content-between">
                  <li class="truncate"><i class="fa-solid fa-location-dot"></i> <%= pool.location %></li>
                  <li class="rating"><i class="fa-solid fa-star"></i> <%= pool.rating %></i></li>
                  <li class="price"><strong><%= pool.price %> €</strong></li>
                </ul>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="flex-grow-0" id="map-container" style="width: 40vw; height: 100vh;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
</div>

app/views/pools/new.html.erb
<div class="new-pool-bg" style="background-image: url('https://images.unsplash.com/uploads/1411599070526e808c923/239f12cc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80')">
  <div class="new-pool">

    <div class="container form-lewagon" >
      <h2>Add a new pool</h2>
      <%= render "form" %>

    </div>
  </div>
</div>

app/views/pools/show.html.erb
<% if @pool.photo.attached? %>
  <div class="banner mb-5" style="background-image: url('<%= cl_image_path @pool.photo.key, crop: :fill %>')"></div>
<% else %>
  <div class="banner mb-5" style="background-image: url('https://images.unsplash.com/photo-1536745511564-a5fa6e596e7b?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=992')"></div>
<% end %>
<div class="container">
  <div class="pool-details">
    <div class="description">

    <%= link_to "< Back to all pools", 'javascript:history.back()' %>
      <%# <%= link_to "< Back to all pools", pools_path %>
      <% if policy(@pool).edit? %>
        <span> | </span>
        <%= link_to 'Edit', edit_pool_path(@pool) %>
        <span> | </span>
        <% if policy(@pool).destroy? %>
          <%= link_to "Delete", delete_pool_path(@pool), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        <% end %>
      <% end %>
      <h1 class="mt-4 mb-3"><%= @pool.name %></h1>
      <ul class="mb-3">
        <li class="category"><%= @pool.category %> | </li>
        <li><i class="fa-solid fa-location-dot"></i> <%= @pool.location %> | </li>
        <li><i class="fa-solid fa-star"></i> <%= @pool.rating %></i></li>
      </ul>
      <p><%= @pool.description %></p>
    </div>

    <% if @pool.user != current_user %>
      <div class="book-pool">

        <h3>Book this pool</h3>
<div data-controller="price-calculator">
        <%= simple_form_for [@pool, @booking] do |f| %>
          <%= f.input :start_date, as: :date, html5: true, input_html: {data: {action: "change->price-calculator#calculatePrice", price_calculator_target: "start"}}%>
          <%= f.input :end_date, as: :date, html5: true, input_html: {data: {action: "change->price-calculator#calculatePrice", price_calculator_target: "end"}} %>
          <hr>
          <div class="d-flex justify-content-between align-items-center">
            <p class="price" data-price-calculator-target="price"><%= @pool.price %> €</p>
            <%= f.button :submit, class: 'btn btn-primary' %>
          </div>
        <% end %>
</div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Thank you for visiting Swim In Pool!
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if request.path == '/' %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-home">
<% else %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<% end %>
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h5>SWIM IN POOL</h5>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto align-items-center">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboards_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "+ New pool", new_pool_path, class: 'btn btn-outline-primary btn-sm' %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://images.unsplash.com/photo-1432251407527-504a6b4174a2?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1160", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>